/*
 * fileX.h - Extended Function Prototypes for Utility Modules
 *
 * This header contains function prototypes for the extended utility modules
 * that provide core functionality to the Conquer strategy game. Originally
 * auto-generated by cextract 1.5, this file provides the interface definitions
 * for utility subsystems including data validation, economic computation,
 * string conversion, memory management, I/O operations, and game mechanics.
 *
 * Key Components:
 *   - Data validation and locking functions (checkX.c)
 *   - Economic computation and production systems (computeX.c)
 *   - String conversion and formatting utilities (convertX.c)
 *   - Configuration file management (customX.c)
 *   - Command execution system (executeX.c)
 *   - Memory management and allocation (memoryX.c)
 *   - Input/output operations (ioX.c)
 *   - Data file persistence (iodataX.c)
 *   - Magic system utilities (magicX.c)
 *   - Mail system formatting (mailX.c)
 *   - Miscellaneous utility functions (miscX.c)
 *   - Movement system calculations (moveX.c)
 *   - Sector management and terrain (sectorX.c)
 *   - Data structure selection utilities (selectX.c)
 *   - Unit manipulation and management (unitsX.c)
 *   - Shared functionality between programs (jointA.c)
 *
 * Integration Notes:
 *   - Used by: All game modules requiring extended functionality
 *   - Used by: Core game engine (A modules) and user interface (G modules)
 *   - Depends on: header.h, dataX.h (core data structures and constants)
 *   - Provides: Complete extended utility API for game functionality
 *
 * Modernization Considerations:
 *   - Legacy ANSI C prototype compatibility macros (PL_) should be removed
 *   - Function prototypes should be converted to modern C2023 syntax
 *   - Parameter types should be explicitly specified instead of using macros
 *   - Include guards should be modernized to standard conventions
 *   - Memory management functions should be reviewed for safety
 *   - File I/O operations should use modern secure practices
 *
 * Historical Notes:
 *   - Auto-generated by cextract 1.5 on Tue Oct 20 18:12:09 1992
 *   - Contains legacy pre-ANSI C compatibility mechanisms
 *   - Represents the complete extended utility API as of original development
 *   - Functions organized by source module for maintenance clarity
 */
/*
 * Legacy ANSI C Compatibility Macros
 *
 * These macros provide compatibility between pre-ANSI C compilers that don't
 * support function prototypes and ANSI C compilers that do. In modern C2023,
 * these should be removed and replaced with standard function prototypes.
 *
 * PL_(x) - Parameter list macro for conditional prototype support
 *   - Expands to 'x' on ANSI C compilers (__STDC__ defined)
 *   - Expands to '( )' on pre-ANSI C compilers (no prototype support)
 *
 * Modernization: Remove PL_ macro usage and use direct function prototypes
 */
#ifndef __CEXTRACT__
#if __STDC__
#define PL_(x) x
#else
#define PL_(x) ( )
#endif /* __STDC__ */

/* ============================================================================
 * DATA VALIDATION AND LOCKING SYSTEM - checkX.c
 * ============================================================================
 * Purpose: File locking, data validation, and multi-user coordination
 * Usage: Data integrity checking, user validation, system verification
 * Notes: Critical system for maintaining data consistency (8 functions total)
 */

/*
 * check_lock - Set or check file lock with optional lock retention
 *
 * Manages file locking for multi-user coordination, preventing simultaneous
 * access to critical game data files. Can check existing locks and optionally
 * set new locks based on the keeplock parameter.
 *
 * Parameters:
 *   filename - Path to file requiring lock protection
 *   keeplock - If true, set lock after checking; if false, check only
 *
 * Returns:
 *   -1 if file already locked by another process
 *   0 or positive value on success (lock ID when keeplock is true)
 */
extern int check_lock PL_(( char * filename, int keeplock ));

/*
 * get_userid - Retrieve current user identification string
 *
 * Attempts to determine the current user's name or identifier from
 * system information, used for user tracking and access control.
 *
 * Parameters:
 *   outname - Buffer to store the retrieved user name
 *
 * Returns:
 *   Pointer to user name string, NULL if unable to determine
 */
extern char * get_userid PL_(( char * outname ));

/*
 * kill_lock - Remove file lock by lock identifier
 *
 * Releases a previously acquired file lock, allowing other processes
 * to access the protected file. Used for cleanup during normal exit
 * or error recovery.
 *
 * Parameters:
 *   fid - Lock identifier returned by check_lock
 *   fname - Filename associated with the lock (for verification)
 */
extern void kill_lock PL_(( int fid, char * fname ));

/*
 * user_exists - Validate user account existence on system
 *
 * Checks if the specified username corresponds to a valid system
 * account, used for user authentication and access validation.
 *
 * Parameters:
 *   who - Username string to validate
 *
 * Returns:
 *   TRUE if user exists on system, FALSE otherwise
 */
extern int user_exists PL_(( char * who ));

/*
 * verify_data - Comprehensive game data integrity validation
 *
 * Performs extensive validation of all game data structures to ensure
 * consistency and detect corruption. Used for debugging and data recovery.
 *
 * Parameters:
 *   __file__ - Source filename for error reporting (__FILE__ macro)
 *   __line__ - Source line number for error reporting (__LINE__ macro)
 */
extern void verify_data PL_(( char * __file__, int __line__ ));

/*
 * verify_ntn - Validate nation data structure integrity
 *
 * Ensures all nation information is valid and consistent, checking
 * for data corruption in nation-specific data structures.
 *
 * Parameters:
 *   __file__ - Source filename for error reporting (__FILE__ macro)
 *   __line__ - Source line number for error reporting (__LINE__ macro)
 */
extern void verify_ntn PL_(( char * __file__, int __line__ ));

/*
 * verify_sct - Validate sector data structure integrity
 *
 * Ensures all sector information contains valid data, checking for
 * inconsistencies in map data and sector properties.
 *
 * Parameters:
 *   __file__ - Source filename for error reporting (__FILE__ macro)
 *   __line__ - Source line number for error reporting (__LINE__ macro)
 */
extern void verify_sct PL_(( char * __file__, int __line__ ));

/*
 * who_is_on - Display list of currently logged-in users
 *
 * Provides system administrator functionality to see which users
 * are currently active in the game system.
 */
extern void who_is_on PL_(( void ));

/* ============================================================================
 * ECONOMIC COMPUTATION ENGINE - computeX.c
 * ============================================================================
 * Purpose: National production, budget calculations, and economic statistics
 * Usage: Economic modeling, resource management, production planning
 * Notes: Core economic engine for game balance and mechanics (20 functions total)
 */

/* National attribute and economics functions */
extern void adjust_attribute PL_(( short * bute_list, int butenum, int amount )); /* Modify national attribute value */
extern void adjust_production PL_(( SHEET_PTR produce_ptr, int fullinfo )); /* Adjust raw material production */
extern void army_reorganize PL_(( void )); /* Reorganize all army unit numbers */
extern int attract_val PL_(( int xloc, int yloc )); /* Calculate sector attractiveness value */
extern int dflt_cityweight PL_(( int ntnnum, CITY_PTR c1_ptr )); /* Default city weighting calculation */
extern void find_area PL_(( int ntnnum )); /* Set nation territorial limit indicators */
extern int find_newarmynum PL_(( int utype )); /* Generate new army unit number by type */
extern itemtype infl_of PL_(( itemtype talon_value )); /* Calculate inflation expense on currency */
extern int merc_costrate PL_(( void )); /* Nation's mercenary cost rate percentage */
extern void mgk_cost_adjust PL_(( int type, itemtype * expenses )); /* Magic system cost adjustments */
extern void ntn_totals PL_(( int nation )); /* Compile nation's city and item totals */
extern int r10_region PL_(( NTN_PTR n1_ptr, CITY_PTR c1_ptr, SCT_PTR s1_ptr )); /* Supply center range (x10) */
extern SHEET_PTR region_consume PL_(( char * cname, int fullinfo )); /* Regional resource consumption */
extern SHEET_PTR region_produce PL_(( char * cname, int fullinfo )); /* Regional resource production */
extern void set_weights PL_(( int recalc )); /* Set nation distribution weights */

/* ============================================================================
 * STRING CONVERSION AND FORMATTING UTILITIES - convertX.c
 * ============================================================================
 * Purpose: Data conversion, string manipulation, and formatting functions
 * Usage: Text processing, data transformation, user interface formatting
 * Notes: Essential utility functions for data presentation (16 functions total)
 */

/* String analysis and character functions */
extern int char_in_str PL_(( char ch, char * str )); /* Check if character exists in string */
extern int completion PL_(( char * s1, char * s2 )); /* Test if s2 completes s1 (strncmp-like) */
extern void convert_kbind PL_(( char * str )); /* Convert text to keybinding representation */
extern void form_str PL_(( char * out_str, char * in_str, int full )); /* Format string for display */
extern int list_magics PL_(( char * out_str, int mcls, long powlist )); /* Format magic powers to string */
extern int non_cntrl PL_(( int ch )); /* Convert control character to normal */
extern int ntn_realname PL_(( char * outstr, int who )); /* Get nation's proper name */
extern long poptoworkers PL_(( long population )); /* Convert population to worker count */
extern int roman_base PL_(( int value )); /* Find roman numeral base value */
extern void roman_number PL_(( char * str, int value )); /* Convert number to roman numerals */
extern int to_cntrl PL_(( int ch )); /* Convert character to control character */
extern int trim_str PL_(( char * str, int killpound )); /* Remove whitespace and comments */
extern int xloc_relative PL_(( int given_xloc )); /* Convert X coordinate to relative */
extern int yloc_relative PL_(( int given_yloc )); /* Convert Y coordinate to relative */

/* ============================================================================
 * CONFIGURATION FILE MANAGEMENT - customX.c
 * ============================================================================
 * Purpose: Configuration file reading, writing, and environment processing
 * Usage: Game settings management, option persistence, environment setup
 * Notes: Simple configuration system for user preferences (3 functions total)
 */

extern void init_datadir PL_(( void )); /* Initialize data directory from datadirname */
extern int read_custom PL_(( char * f_str )); /* Read configuration options from file */
extern void read_environ PL_(( void )); /* Parse conquer environment variables */

/* ============================================================================
 * COMMAND EXECUTION SYSTEM - executeX.c
 * ============================================================================
 * Purpose: Player command file processing and batch execution
 * Usage: Automated command processing, scripted game actions
 * Notes: Critical system for turn-based command execution (1 function)
 */

/*
 * execute - Process player command file for automated actions
 *
 * Reads and executes commands from a player's command file, enabling
 * batch processing of game actions for turn-based gameplay.
 *
 * Parameters:
 *   cntry - Nation number for command processing
 *
 * Returns:
 *   0 for no command file found
 *   1 for successful execution
 *   >1 or -1 for various error conditions
 */
extern int execute PL_(( int cntry ));

/* ============================================================================
 * HEXAGONAL MAP UTILITIES - hexmapX.c
 * ============================================================================
 * Purpose: Hexagonal map calculations and geometric operations
 * Usage: Map distance calculations, range operations, geometric queries
 * Notes: Essential hexagonal geometry utilities (2 functions total)
 */

extern void map_loop PL_(( int xcent, int ycent, int range, FNCV2 perform_func )); /* Execute function on sectors within range */
extern int map_within PL_(( int xa, int ya, int xb, int yb, int range )); /* Test if locations within given range */

/* ============================================================================
 * INPUT/OUTPUT OPERATIONS - ioX.c
 * ============================================================================
 * Purpose: Generic I/O operations, user input, screen management
 * Usage: Terminal control, user interaction, input validation
 * Notes: Core I/O system for user interface functionality (29 functions total)
 */

/* Display and screen management functions */
extern void bottommsg PL_(( char * str )); /* Display message without waiting for key */
extern void clear_bottom PL_(( int l )); /* Clear bottom message area */
extern void cq_bye PL_(( int status )); /* Reset display and exit with status */
extern void cq_init PL_(( char * progname )); /* Initialize curses display system */
extern void cq_reset PL_(( void )); /* Terminate curses display gracefully */
extern int cr_or_y PL_(( void )); /* Check for 'y', 'Y', or carriage return */
extern int do_redraw PL_(( void )); /* Alternative screen refresh method */
extern void errorbar PL_(( char * str1, char * str2 )); /* Display highlighted error bar */
extern int errormsg PL_(( char * str )); /* Display error message and wait for key */
extern void fork_edit_on_file PL_(( char * fname, char * pstr )); /* Launch editor on file copy */

/* Input validation and data entry functions */
extern int get_aclass PL_(( void )); /* Get army class interactively */
extern int get_atype PL_(( void )); /* Get army type interactively */
extern double get_double PL_(( int allowneg )); /* Read double value with validation */
extern int get_month PL_(( void )); /* Get month value interactively */
extern long get_number PL_(( int allowneg )); /* Read integer with validation */
extern int get_option PL_(( void )); /* Enter option string selection */
extern int get_pass PL_(( char * str )); /* Get password without echo */
extern int get_speed PL_(( void )); /* Get speed value interactively */
extern int get_status PL_(( void )); /* Get status value interactively */
extern int get_string PL_(( char * str, int stype, int max_len )); /* Read string with type validation */

/* Character I/O and display functions */
extern void hip_string PL_(( char * str_in, int keychar, int bolden )); /* Highlight character in parentheses */
extern int next_char PL_(( void )); /* Get next input character */
extern int one_char PL_(( char * set, int fold )); /* Get character from allowed set */
extern int presskey PL_(( void )); /* Display message and wait for key */
extern void push_char PL_(( int ch_in )); /* Push character onto input stack */
extern void show_char PL_(( char ch, int full )); /* Display character at cursor */
extern void show_str PL_(( char * str, int full )); /* Display string at cursor */
extern void unshow_char PL_(( char ch, int full )); /* Remove character from display */
extern void win_size_change PL_(( void )); /* Handle window size change signal */
extern int y_or_n PL_(( void )); /* Check for 'y' or 'Y' response */

/* ============================================================================
 * DATA FILE PERSISTENCE - iodataX.c
 * ============================================================================
 * Purpose: World data file reading, writing, and file management
 * Usage: Game state persistence, data file operations, file utilities
 * Notes: Critical system for game data storage and recovery (6 functions total)
 */

extern int exists PL_(( char * file )); /* Test for file existence */
extern void fput_string PL_(( char * outstr, FILE * filep )); /* Safe fputs with error checking */
extern int move_file PL_(( char * from, char * to )); /* Rename/move file (0=success, non-zero=fail) */
extern int read_data PL_(( void )); /* Read world data from data file */
extern void syserr_msg PL_(( char * estr )); /* Display system error message */
extern void write_data PL_(( void )); /* Write world data to data file */

/* ============================================================================
 * MAGIC SYSTEM UTILITIES - magicX.c
 * ============================================================================
 * Purpose: Magic power management, spell effects, and magical calculations
 * Usage: Spell processing, power enhancement, magical combat modifiers
 * Notes: Core magic system implementation (6 functions total)
 */

extern void add_powers PL_(( int powtype, long powlist )); /* Apply magical power enhancements */
extern void kill_powers PL_(( int powtype, long powlist )); /* Remove magical power enhancements */
extern int magic_ok PL_(( int magic_type, int new_mint )); /* Validate magic power for class */
extern int mgk_sctval PL_(( NTN_PTR n1_ptr, int x, int y )); /* Calculate magical combat bonus */
extern long rand_magic PL_(( int magic_type )); /* Generate random magical power */

/* ============================================================================
 * MAIL SYSTEM FORMATTING - mailX.c
 * ============================================================================
 * Purpose: Mail message formatting, delivery, and memory management
 * Usage: In-game messaging, mail composition, message handling
 * Notes: Essential communication system utilities (5 functions total)
 */

extern void deliver_mail PL_(( void )); /* Send current mail to target countries */
extern void free_mail PL_(( void )); /* Deallocate all mail memory */
extern void init_mail PL_(( void )); /* Initialize mail storage structure */
extern void kill_mail PL_(( void )); /* Remove current mail message */
extern void mail_header PL_(( char * nnstr, char * nkstr, char * subj, char * dstr, int statval )); /* Send mail header */

/* ============================================================================
 * MEMORY MANAGEMENT SYSTEM - memoryX.c
 * ============================================================================
 * Purpose: Dynamic memory allocation, data structure management, sorting
 * Usage: Object creation/destruction, memory allocation, data organization
 * Notes: Core memory management for all game entities (30+ functions total)
 */

/* ALIGN_ARMYNEAR -- Assign location pointers properly */
extern void align_armynear PL_(( void ));

/* ALIGN_DATA -- Destroy nations and count elements */
extern void align_data PL_(( void ));

/* ARMY_SORT() -- Resort army list into ascending order and connect
                  armies in same sector by the near structure       */
extern void army_sort PL_(( int skipnears ));

/* CITY_SORT() -- Resort city list into ascending order */
extern void city_sort PL_(( void ));

/* CLR_MEMORY -- Clear out a patch of memory */
extern void clr_memory PL_(( char * mem_ptr, int len ));

/* CRT_ARMY -- Build an army unit assigning an id number to it
                  based on the type of the new unit.              */
extern ARMY_PTR crt_army PL_(( int utype ));

/* CRT_CITY -- Add a new city to the nation city list */
extern CITY_PTR crt_city PL_(( char * cname ));

/* CRT_CVN -- Add a new caravan to the nation list */
extern CVN_PTR crt_cvn PL_(( void ));

/* CRT_DMODE -- Initialize a new display mode into display mode list */
extern DMODE_PTR crt_dmode PL_(( char * dmodename ));

/* CRT_ITEM -- Add a new item to the nation list */
extern ITEM_PTR crt_item PL_(( void ));

/* Entity creation and initialization functions */
extern NAVY_PTR crt_navy PL_(( void )); /* Add a new navy to the nation list */
extern NTN_PTR crt_ntn PL_(( char * ntnname, int actval )); /* Initialize a new nation into the world */

/* Entity destruction and cleanup functions */
extern void dest_army PL_(( int idnum )); /* Remove an army unit from the army list */
extern void dest_city PL_(( char * cname )); /* Remove a city from the national city list */
extern void dest_cvn PL_(( int idnum )); /* Remove a caravan from the caravan list */
extern void dest_item PL_(( int idnum )); /* Remove an item from the national commodity list */
extern void dest_navy PL_(( int idnum )); /* Remove a navy unit from the navy list */
extern void dest_ntn PL_(( char * nname )); /* Free memory associated with a nation structure */

/* Memory allocation functions for game entities */
extern ARMY_PTR new_army PL_(( void )); /* Allocate space for a new army unit */
extern CITY_PTR new_city PL_(( void )); /* Allocate space for a new city */
extern CVN_PTR new_cvn PL_(( void )); /* Allocate space for a new caravan unit */
extern DMODE_PTR new_dmode PL_(( void )); /* Allocate space for a new display entry */
extern ITEM_PTR new_item PL_(( void )); /* Allocate space for a new item */
extern MAP_PTR new_map PL_(( void )); /* Allocate space for a new unit mapping structure */
extern NAVY_PTR new_navy PL_(( void )); /* Allocate space for a new naval unit */
extern NTN_PTR new_ntn PL_(( void )); /* Allocate space for a new nation */
extern UNUM_PTR new_unum PL_(( void )); /* Allocate space for a new unit numbering structure */

/* World-size memory allocation functions */
extern char * new_mapchar PL_(( char * mem_ptr )); /* Allocate character memory the size of the world */
extern long * new_maplong PL_(( long * mem_ptr )); /* Allocate long integer memory the size of the world */
extern short * new_mapshort PL_(( short * mem_ptr )); /* Allocate short integer memory the size of the world */

/* Multi-dimensional memory allocation utilities */
extern char ** m2alloc PL_(( int nrows, int ncols, int entrysize )); /* Allocate a two dimensional array of memory */

/* Data structure sorting and organization functions */
extern void cvn_sort PL_(( void )); /* Resort caravan list into ascending order */
extern void item_sort PL_(( void )); /* Resort item list into ascending order */
extern void navy_sort PL_(( void )); /* Resort navy list into ascending order */
extern void ntn_sort PL_(( void )); /* Place nations in alphabetical order and remove empty slots */

/* Unit numbering system functions */
extern void unum_defaults PL_(( void )); /* Set the default values for unit numbering */

/* ============================================================================
 * MISCELLANEOUS UTILITIES - miscX.c
 * ============================================================================
 * Purpose: General utility functions used in both programs
 * Usage: Time functions, validation, random number generation, string comparison
 * Notes: Shared utility functions for cross-program functionality (12 functions total)
 */

/* Game initialization and spell generation */
extern void give_spellcasters PL_(( void )); /* Generate spell casters for each nation */

/* Display and interface utilities */
extern int hl_targets PL_(( int style )); /* Check if highlight method needs a target value */
extern char * mach_time PL_(( void )); /* Return a pointer to a string containing the date */

/* Data validation functions */
extern int markok PL_(( int mark, int racetype, int showwhy )); /* Validate nation mark for race type */

/* Random number generation system */
extern void nrand_seed PL_(( void )); /* Set the storage value for the nrand_val() function */
extern long nrand_val PL_(( long limit, long adj )); /* Adjusted random value for reproducible results */
extern void rand_seed PL_(( void )); /* Seed the random number generator */
extern long rand_val PL_(( int limit )); /* Generate random number from 0 to N-1 */
extern int rand_tgood PL_(( int tg_class, int minval )); /* Select random tradegood of given class and minimum value */

/* Bitwise operations and utility functions */
extern int num_bits_on PL_(( long lng_list )); /* Return the number of active bits in the given long */

/* String comparison utilities */
extern int str_ntest PL_(( char * s1, char * s2, int num )); /* Case-insensitive strncmp function */
extern int str_test PL_(( char * s1, char * s2 )); /* Case-insensitive strcmp function */

/* ============================================================================
 * UNIT MOVEMENT CALCULATIONS - moveX.c
 * ============================================================================
 * Purpose: Unit movement cost calculations and mobility management
 * Usage: Movement validation, cost computation, mobility potential setting
 * Notes: Essential movement mechanics for all unit types (3 functions total)
 */

extern int move_cost PL_(( int x, int y, int type )); /* Calculate movement cost for specified unit type */
extern void set_movepotential PL_(( int type )); /* Set the movement potential for a unit */

/* ============================================================================
 * SECTOR MANAGEMENT AND CALCULATIONS - sectorX.c
 * ============================================================================
 * Purpose: Sector analysis, resource management, and terrain calculations
 * Usage: Combat calculations, resource distribution, sector modification
 * Notes: Core world map sector functionality (30+ functions total)
 */

/* Combat and defensive calculations */
extern int defense_val PL_(( int x, int y )); /* Compute the defensive value for a sector */
extern int exposure_value PL_(( NTN_PTR n1_ptr, SCT_PTR s1_ptr )); /* Amount of exposure troops face in a sector */
extern int fort_val PL_(( int x, int y )); /* Compute the fortification value of a sector */

/* Sector designation and validation */
extern int desg_ok PL_(( int x, int y, int dtype, int verbal )); /* Determine if major designation is valid for sector */
extern int is_habitable PL_(( int x, int y )); /* Determine if a sector can be lived in */
extern int mindesg_ok PL_(( int x, int y, int mdtype, int verbal )); /* Check if minor designation is valid for sector */

/* Vision and information distortion */
extern long distort_vision PL_(( int xval, int yval, long trueval, long distval )); /* Distort numerical values based on vision */
extern int tg_ok PL_(( SCT_PTR sptr, int nation )); /* Check if trade good can be seen by given nation */

/* Resource generation and assignment */
extern void getjewel PL_(( SCT_PTR sptr )); /* Assign value and type to a sector's jewels */
extern void getmetal PL_(( SCT_PTR sptr )); /* Assign a metal value to a given sector */
extern void getspell PL_(( SCT_PTR sptr )); /* Assign magic spell enchantment to sectors */

/* Resource valuation functions */
extern int jewel_value PL_(( SCT_PTR sptr )); /* Return the value of the jewels in the sector */
extern int magic_value PL_(( SCT_PTR sptr )); /* Return the value of the spells in the sector */
extern int metal_value PL_(( SCT_PTR sptr )); /* Return the value of the metals in the sector */
extern int tofood PL_(( SCT_PTR sptr, int cntry )); /* Compute the food value of a sector */
extern int towood PL_(( SCT_PTR sptr, int cntry )); /* Compute the lumber value of a sector */

/* Designation cost calculations */
extern ITEM_PTR majdesg_costs PL_(( int which, int x, int y, int verbal )); /* Calculate resource price to build major designation */
extern ITEM_PTR mindesg_costs PL_(( int which, int x, int y, int verbal )); /* Compute the cost for minor designation */

/* Resource management and distribution */
extern ITEM_PTR find_resources PL_(( int xloc, int yloc, int insect_only )); /* Build item_struct holding all nearby resources */
extern void sector_consume PL_(( int xloc, int yloc, SHEET_PTR out_ptr )); /* Calculate all of the sector needs */
extern void sector_produce PL_(( int xloc, int yloc, SHEET_PTR out_ptr )); /* Calculate all of the production ability */
extern int send_resources PL_(( int xloc, int yloc, ITEM_PTR give_ptr, int insect )); /* Redistribute materials to nearby supply centers */
extern int take_resources PL_(( int xloc, int yloc, ITEM_PTR take_ptr, int insect )); /* Remove resources from neighboring areas */

/* Sector analysis and utility functions */
extern void rand_sector PL_(( int x, int y, int range, int nowater, int visionrand )); /* Set global coordinates to random locale */
extern void sct_cost_adjust PL_(( int type, SCT_PTR s1_ptr, itemtype * expenses )); /* Adjustment due to what is in the sector */
extern int s_uselevel PL_(( SCT_PTR s1_ptr )); /* Usage level of the sector within its discipline */

/* ============================================================================
 * DATA STRUCTURE SELECTION - selectX.c
 * ============================================================================
 * Purpose: Quick reference and lookup functions for game data structures
 * Usage: Entity retrieval by ID, name, or location; data structure navigation
 * Notes: Essential lookup utilities for game object access (13 functions total)
 */

/* ARMYBYNUM -- Retrieve pointer to a given army number */
extern ARMY_PTR armybynum PL_(( int idnum ));

/* CITYBYLOC -- Check for a city by location */
extern CITY_PTR citybyloc PL_(( NTN_PTR n1_ptr, int x, int y ));

/* CITYBYNAME -- Check for a city by name */
extern CITY_PTR citybyname PL_(( char * str ));

/* CVNBYNUM -- Retrieve pointer to a given caravan number */
extern CVN_PTR cvnbynum PL_(( int idnum ));

/* ITEMBYARMY -- Search for the army number in the item list */
extern ITEM_PTR itembyarmy PL_(( int idnum ));

/* ITEMBYCVN -- Search for the caravan number in the item list */
extern ITEM_PTR itembycvn PL_(( int idnum ));

/* ITEMBYNAVY -- Search for the navy number in the item list */
extern ITEM_PTR itembynavy PL_(( int idnum ));

/* ITEMBYNUM -- Retrieve a commodity by its given number */
extern ITEM_PTR itembynum PL_(( int idnum ));

/* ITEMBYSCT -- Find the next item pointer to a sector */
extern ITEM_PTR itembysct PL_(( ITEM_PTR i_list, int x, int y, int type ));

/* NAVYBYNUM -- Retrieve pointer to a given navy number */
extern NAVY_PTR navybynum PL_(( int idnum ));

/* NTNBYNAME -- Check for a nation by name or number */
extern NTN_PTR ntnbyname PL_(( char * str ));

/* UCLASSBYNAME -- Retrieve a unit class by the name string */
extern int uclassbyname PL_(( char * match_str ));

/* UNITBYNAME -- Retrieve a unit number by the name string */
extern int unitbyname PL_(( char * match_str ));

/* unitsX.c: Misc. manipulation routines for army, navy and caravan units */

/* ARMIES_IN_SECTOR -- Report the number of army units in a sector */
extern int armies_in_sector PL_(( int natn, int xloc, int yloc ));

/* ARMY_CAPTSIZE -- Strength of the unit in relation to sector taking */
extern long army_captsize PL_(( ARMY_PTR a1_ptr, int takefigure ));

/* ARMY_LOAD -- The amount of load within an army unit */
extern long army_load PL_(( ARMY_PTR a_ptr ));

/* ARMY_MVPTS -- Return the starting movement for the specified unit */
extern int army_mvpts PL_(( NTN_PTR n1_ptr, ARMY_PTR a1_ptr ));

/* ARMY_RENUM -- Renumber the current army unit in the current nation */
extern void army_renum PL_(( int newnum ));

/* ARMY_SHIPLEADER -- Return leader if onboard otherwise EMPTY_HOLD */
extern int army_shipleader PL_(( ARMY_PTR a1_ptr ));

/* unitsX.c: Unit manipulation and management functions (remainder) */

/* army_spellpts - Calculate maximum spell points for a unit */
extern int army_spellpts PL_(( NTN_PTR n1_ptr, ARMY_PTR a1_ptr ));

/* army_support - Calculate support costs for an army unit */
extern void army_support PL_(( ARMY_PTR a1_ptr, itemtype * out_costs, int amount ));

/* army_worksize - Calculate unit strength for building potential */
extern long army_worksize PL_(( ARMY_PTR a1_ptr ));

/* a_issupplyable - Check if army unit can be supplied from location */
extern int a_issupplyable PL_(( ARMY_PTR a1_ptr, int x, int y, int sayit ));

/* cargo_holds - Get number of cargo holds in ship information */
extern int cargo_holds PL_(( int shipinfo ));

/* check_leader - Verify if leader is actively leading units */
extern int check_leader PL_(( int idnum ));

/* cvns_in_sector - Count caravans in specified sector */
extern int cvns_in_sector PL_(( int natn, int xloc, int yloc ));

/* cvn_carrying - Check if caravan has cargo onboard */
extern int cvn_carrying PL_(( CVN_PTR c1_ptr ));

/* cvn_load - Calculate total load within caravan unit */
extern long cvn_load PL_(( CVN_PTR v_ptr ));

/* cvn_mvpts - Calculate caravan movement speed */
extern int cvn_mvpts PL_(( NTN_PTR nat_ptr, CVN_PTR c_ptr ));

/* cvn_redocosts - Calculate caravan repair costs */
extern void cvn_redocosts PL_(( CVN_PTR v1_ptr, itemtype * out_costs ));

/* cvn_renum - Renumber caravan unit in current nation */
extern void cvn_renum PL_(( int newnum ));

/* cvn_support - Calculate caravan supply requirements */
extern void cvn_support PL_(( CVN_PTR v1_ptr, itemtype * out_costs, int amount ));

/* defaultunit - Get default unit type for drafting */
extern int defaultunit PL_(( void ));

/* getminleader - Get minor leader for national class */
extern int getminleader PL_(( int class ));

/* getruler - Get major leader for national class */
extern int getruler PL_(( int class ));

/* group_stat - Get status of specified group */
extern int group_stat PL_(( int idnum ));

/* heal_rate - Calculate healing percentage for army unit */
extern int heal_rate PL_(( NTN_PTR n1_ptr, ARMY_PTR a1_ptr ));

/* main_leader - Get primary leader of a group */
extern ARMY_PTR main_leader PL_(( int idnum ));

/* make_madunit - Create army unit at specified location */
extern int make_madunit PL_(( int own, int atype, int asize, int axloc, int ayloc ));

/* max_numunit - Calculate maximum possible unit size */
extern long max_numunit PL_(( NTN_PTR n1_ptr, CITY_PTR c1_ptr, int utype, int spts ));

/* may_upgrade - Check if army unit can be upgraded */
extern int may_upgrade PL_(( NTN_PTR n1_ptr, CITY_PTR c1_ptr, int utype, int men ));

/* men_ingarrison - Count garrisoned soldiers in sector */
extern long men_ingarrison PL_(( int x, int y, int onlyaair ));

/* men_ingroup - Count soldiers in specified group */
extern int men_ingroup PL_(( int idnum, int onlyaair ));

/* mtrls_load - Calculate load weight of raw materials */
extern long mtrls_load PL_(( itemtype * m_ptr ));

/* navies_in_sector - Count naval units in specified sector */
extern int navies_in_sector PL_(( int natn, int xloc, int yloc ));

/* navy_addships - Add ships to fleet element */
extern int navy_addships PL_(( uns_short info, int sh_size, int nships ));

/* navy_carrying - Check if naval unit has cargo onboard */
extern int navy_carrying PL_(( NAVY_PTR n1_ptr ));

/* navy_holds - Calculate cargo holds in fleet ship class */
extern int navy_holds PL_(( NAVY_PTR n1_ptr, int classnum ));

/* navy_mvpts - Calculate naval fleet movement speed */
extern int navy_mvpts PL_(( NTN_PTR nat_ptr, NAVY_PTR nvy_ptr ));

/* navy_redocosts - Calculate naval unit repair costs */
extern void navy_redocosts PL_(( NAVY_PTR n1_ptr, itemtype * out_costs ));

/* navy_renum - Renumber naval unit in current nation */
extern void navy_renum PL_(( int newnum ));

/* navy_subships - Remove ships from fleet element */
extern int navy_subships PL_(( uns_short info, int sh_size, int nships ));

/* navy_support - Calculate naval unit supply requirements */
extern void navy_support PL_(( NAVY_PTR n1_ptr, itemtype * out_costs, int amount ));

/* newslotnumber - Set default numbering for unit slots */
extern void newslotnumber PL_(( int base, int idnum, int numtype ));

/* n_issupplyable - Check if naval unit can be supplied from location */
extern int n_issupplyable PL_(( NAVY_PTR n1_ptr, int x, int y, int sayit ));

/* rand_monstunit - Generate random monster unit by strength limit */
extern int rand_monstunit PL_(( int maxstrength ));

/* real_stat - Get actual status of army unit */
extern int real_stat PL_(( ARMY_PTR a1_ptr ));

/* resetnumbers - Clear default unit numbering scheme */
extern void resetnumbers PL_(( void ));

/* set_armycosts - Calculate costs for creating army unit */
extern void set_armycosts PL_(( NTN_PTR n1_ptr, itemtype * cost_ptr, int type, int size ));

/* set_grploc - Assign location to entire unit group */
extern void set_grploc PL_(( int idnum, int x, int y ));

/* set_grpmove - Assign movement parameters to unit group */
extern void set_grpmove PL_(( int idnum, int speed, int mval ));

/* set_upgcosts - Calculate costs for upgrading army unit */
extern void set_upgcosts PL_(( NTN_PTR n1_ptr, ARMY_PTR a1_ptr, itemtype * cost_ptr, int newtype ));

/* ships_in_sector - Count ships in specified sector */
extern int ships_in_sector PL_(( int x, int y ));

/* startnumber - Parse and assign starting unit number */
extern int startnumber PL_(( char * str, char * estr ));

/* start_unitsply - Get standard starting supply for new units */
extern int start_unitsply PL_(( void ));

/* units_in_sector - Count all unit types in sector for nation */
extern int units_in_sector PL_(( int natn, int x, int y ));

/* unit_basenum - Get base unit number for unit type */
extern int unit_basenum PL_(( int utype ));

/* unum_copydefault - Copy default unit numbering scheme */
extern void unum_copydefault PL_(( void ));

/* utype_mayuse - Check if nation can use specified unit type */
extern int utype_mayuse PL_(( NTN_PTR n1_ptr, int utype ));

/* utype_ok - Validate unit type for city and nation */
extern int utype_ok PL_(( NTN_PTR n1_ptr, CITY_PTR c1_ptr, int utype, int upg_men, int eout ));

/* v_issupplyable - Check if caravan can be supplied from location */
extern int v_issupplyable PL_(( CVN_PTR v1_ptr, int x, int y, int sayit ));

/* wagons_in_sector - Count caravan wagons in specified sector */
extern int wagons_in_sector PL_(( int x, int y ));

/* wall_patrol - Check if army unit is acting as wall patrol */
extern int wall_patrol PL_(( int cntry, ARMY_PTR a1_ptr ));

/* jointA.c: Shared functionality between game programs */

/* bind_func - Get string name for specified function number */
extern char * bind_func PL_(( int which ));

/* check_spells - Execute spell effects at location */
extern void check_spells PL_(( int spellnum, int xloc, int yloc ));

/* dflt_disp_setup - Configure default display settings */
extern void dflt_disp_setup PL_(( char * str, char * fstr, int lnum ));

/* display_setup - Configure display modes and settings */
extern void display_setup PL_(( char * str, char * fstr, int lnum ));

/* hangup - Signal handler for connection termination */
extern void hangup PL_(( int sig ));

/* keysys_setup - Configure keyboard binding system */
extern void keysys_setup PL_(( int type, char * str, char * fstr, int lnum ));

#undef PL_
#endif /* __CEXTRACT__ */
