/*
 * fileG.h - User Interface Function Prototypes
 *
 * This header contains function prototypes for the user interface modules
 * that implement the interactive gameplay systems of the Conquer strategy game.
 * Originally auto-generated by cextract 1.5, this file provides the interface
 * definitions for UI subsystems including display management, input handling,
 * unit manipulation, information screens, and player interaction systems.
 *
 * Key Components:
 *   - User interface function prototypes from mainG.c through time_ckG.c
 *   - Display and map rendering system interfaces
 *   - Unit manipulation and command processing interfaces
 *   - Information display and reporting system interfaces
 *   - Input handling and key binding system interfaces
 *   - File I/O and data management UI interfaces
 *
 * Integration Notes:
 *   - Used by: UI modules requiring cross-module function calls
 *   - Used by: Game engine modules needing UI functionality
 *   - Depends on: header.h, dataG.h (UI data structures and constants)
 *   - Provides: Complete user interface API for all interactive systems
 *
 * Modernization Considerations:
 *   - Legacy ANSI C prototype compatibility macros (PL_) should be removed
 *   - Function prototypes should be converted to modern C2023 syntax
 *   - Parameter types should be explicitly specified instead of using macros
 *   - Include guards should be modernized to standard conventions
 *   - UI function documentation should be enhanced with usability information
 *
 * Historical Notes:
 *   - Auto-generated by cextract 1.5 on Tue Oct 20 18:11:54 1992
 *   - Contains legacy pre-ANSI C compatibility mechanisms
 *   - Represents the complete user interface API as of original development
 */

/*
 * Legacy ANSI C Compatibility Macros
 *
 * These macros provide compatibility between pre-ANSI C compilers that don't
 * support function prototypes and ANSI C compilers that do. In modern C2023,
 * these should be removed and replaced with standard function prototypes.
 *
 * PL_(x) - Parameter list macro for conditional prototype support
 *   - Expands to 'x' on ANSI C compilers (__STDC__ defined)
 *   - Expands to '( )' on pre-ANSI C compilers (no prototype support)
 *
 * Modernization: Remove PL_ macro usage and use direct function prototypes
 */
#ifndef __CEXTRACT__
#if __STDC__
#define PL_(x) x
#else
#define PL_(x) ( )
#endif /* __STDC__ */

/* ============================================================================
 * MAIN UI PROGRAM INTERFACE - mainG.c
 * ============================================================================
 * Purpose: Main user interface entry point and command processing
 * Usage: UI initialization, command parsing, and main game loop
 * Notes: Primary UI controller for interactive gameplay
 */

/*
 * main - UI program entry point and command processor
 *
 * Main entry point for the user interface that handles command-line
 * processing, initializes the interactive game systems, and manages
 * the main game loop for player interaction and input processing.
 *
 * Parameters:
 *   argc - Number of command-line arguments
 *   argv - Array of command-line argument strings
 *
 * Returns:
 *   0 on successful completion, non-zero on error
 */
extern int main PL_(( int argc, char ** argv ));

/* ============================================================================
 * ARMY MANIPULATION INTERFACE - armyG.c
 * ============================================================================
 * Purpose: Interactive army unit management and manipulation
 * Usage: Army creation, modification, supply, and command processing
 * Notes: User interface for army unit operations (13 functions total)
 */

extern int aunit_numbering PL_(( void )); /* Army unit auto-numbering system */
extern void disb_army PL_(( ARMY_PTR a1_ptr )); /* Disband army unit */
extern void ext_armycmd PL_(( int armie )); /* Extended army commands */
extern int supply_army PL_(( ARMY_PTR a1_ptr, int level, int doquery )); /* Set army supply level */
extern void ungroup_scouts PL_(( int grpnum )); /* Remove scouts from group */

/* ============================================================================
 * CARAVAN MANIPULATION INTERFACE - caravanG.c
 * ============================================================================
 * Purpose: Interactive caravan unit management and trade operations
 * Usage: Caravan creation, repair, cargo management, and trading
 * Notes: User interface for caravan unit operations (12 functions total)
 */

extern void cvn_repair PL_(( CVN_PTR v1_ptr )); /* Repair caravan unit */
extern void cvn_transport PL_(( CVN_PTR v1_ptr )); /* Load/unload caravan cargo */
extern void disb_cvn PL_(( CVN_PTR v1_ptr )); /* Disband caravan unit */
extern void ext_cvncmd PL_(( int cvan )); /* Extended caravan commands */
extern void ext_cvninfo PL_(( CVN_PTR v1_ptr )); /* Extended caravan information */
extern int supply_cvn PL_(( CVN_PTR v1_ptr, int level, int doquery )); /* Set caravan supply level */

/* ============================================================================
 * CUSTOMIZATION INTERFACE - customG.c
 * ============================================================================
 * Purpose: User configuration and customization file management
 * Usage: Key binding setup, option configuration, and settings persistence
 * Notes: User interface for game customization (7 functions total)
 */

extern int allkeys_check PL_(( void )); /* Validate all key bindings */
extern void allkeys_init PL_(( void )); /* Initialize all key bindings */
extern int write_custom PL_(( char * fname )); /* Write configuration file */

/* ============================================================================
 * DISPLAY AND MAP RENDERING SYSTEM - displayG.c
 * ============================================================================
 * Purpose: Map display, highlighting, and visual customization system
 * Usage: Screen rendering, map visualization, and display mode management
 * Notes: Core display engine for game visualization (18 functions total)
 */

/* Display mode and highlighting functions */
extern int adj_display PL_(( void )); /* Select highlight/display mode */
extern int change_view PL_(( void )); /* Adjust display character interactively */
extern int custom_display PL_(( void )); /* Interactive display customization */
extern int get_hd_info PL_(( int hilitep )); /* Get highlight/display selection */

/* Highlighting control functions */
extern int hl_all PL_(( void )); /* Change all highlights */
extern int hl_current PL_(( void )); /* Change current focus highlight */
extern int hl_horz PL_(( void )); /* Change horizontal highlighting */
extern int hl_ullr PL_(( void )); /* Change upper-left/lower-right highlights */
extern int hl_urll PL_(( void )); /* Change upper-right/lower-left highlights */
extern int hl_vert PL_(( void )); /* Change vertical highlighting */

/* Screen layout and rendering functions */
extern void makebottom PL_(( void )); /* Place standard display at screen bottom */
extern void makemap PL_(( void )); /* Display visible map to screen */
extern void makeside PL_(( int alwayssee, int moveind )); /* Show sector info sidebar */
extern int recenter_screen PL_(( void )); /* Recenter current location */
extern int shift_focus PL_(( void )); /* Shift focus to next position */
extern int shift_rfocus PL_(( void )); /* Shift focus to previous position */
extern int side_troops PL_(( int start_pos, int max_pos, int show_all )); /* Display troops along edge */
extern int toggle_infomode PL_(( void )); /* Toggle information mode */
extern int troop_listing PL_(( void )); /* List troops in sector */
extern int zoom_in PL_(( void )); /* Increase map detail */
extern int zoom_out PL_(( void )); /* Decrease map detail */

/* ============================================================================
 * EMAIL SYSTEM INTERFACE - emailG.c
 * ============================================================================
 * Purpose: Mail editor for sending interactive messages
 * Usage: Email composition, message editing, mail transmission
 * Notes: Interactive mail editor with key binding system (26 functions total)
 */

/* ALIGN_EMAIL_KEYS -- Align all of the mail editor keys */
extern void align_email_keys PL_(( void ));

/* EMAIL_CLOSE -- Free allocated space and remove all set locks */
extern void email_close PL_(( void ));

/* EMAIL_INIT -- Initialize the bindings */
extern int email_init PL_(( void ));

/* EMAIL_PARSE -- Main interface for sending mail; message in cur_message */
extern void email_parse PL_(( void ));

/* ============================================================================
 * UNIT ENLISTMENT INTERFACE - enlistG.c
 * ============================================================================
 * Purpose: Unit creation system for armies, navies, and caravans
 * Usage: Unit recruitment, military/economic unit creation
 * Notes: Core unit creation interface (7 functions total)
 */

/* ENLIST -- Select whether to enlist armies, navies or caravans */
extern int enlist PL_(( void ));

/* ============================================================================
 * HEXAGONAL MAP DISPLAY SYSTEM - hexmapG.c
 * ============================================================================
 * Purpose: Hexagonal map navigation, cursor control, and sector display
 * Usage: Map navigation, cursor movement, and sector visualization
 * Notes: Core hexagonal map display engine (32 functions total)
 */

/* Map positioning and navigation */
extern void centermap PL_(( void )); /* Center current sector on screen */
extern void coffmap PL_(( void )); /* Check cursor bounds */
extern int mark_sector PL_(( void )); /* Mark current sector position */
extern int recenter_ntn PL_(( void )); /* Realign relative center */

/* Directional movement functions (8 directions) */
extern int go_east PL_(( void )); /* Move cursor east */
extern int go_ne PL_(( void )); /* Move cursor northeast */
extern int go_north PL_(( void )); /* Move cursor north */
extern int go_nw PL_(( void )); /* Move cursor northwest */
extern int go_se PL_(( void )); /* Move cursor southeast */
extern int go_south PL_(( void )); /* Move cursor south */
extern int go_sw PL_(( void )); /* Move cursor southwest */
extern int go_west PL_(( void )); /* Move cursor west */

/* Screen scrolling functions (8 directions) */
extern int scr_east PL_(( void )); /* Scroll screen east */
extern int scr_ne PL_(( void )); /* Scroll screen northeast */
extern int scr_north PL_(( void )); /* Scroll screen north */
extern int scr_nw PL_(( void )); /* Scroll screen northwest */
extern int scr_se PL_(( void )); /* Scroll screen southeast */
extern int scr_south PL_(( void )); /* Scroll screen south */
extern int scr_sw PL_(( void )); /* Scroll screen southwest */
extern int scr_west PL_(( void )); /* Scroll screen west */

/* Display calculation and rendering */
extern void hex_init PL_(( void )); /* Initialize hex-map display */
extern void hex_recalc PL_(( void )); /* Recalculate hex-map information */
extern int max_xcurs PL_(( void )); /* Determine maximum X cursor value */
extern int max_ycurs PL_(( int xval )); /* Determine maximum Y cursor value */
extern int on_screen PL_(( int x, int y )); /* Check if sector on screen */
extern void print_map PL_(( int widemap )); /* Print map to output */
extern void see_around PL_(( int x, int y )); /* Show surrounding sectors */
extern void show_cursor PL_(( void )); /* Position cursor properly */
extern void show_sect PL_(( int x, int y, int x_loc, int y_loc, int method )); /* Show sector at position */
extern void whatcansee PL_(( void )); /* Track map/screen visibility */

/* ============================================================================
 * INFORMATION EDITING INTERFACE - ieditG.c
 * ============================================================================
 * Purpose: Information display editing and modification functions
 * Usage: Data editing, information modification, god mode adjustments
 * Notes: Specialized editing interface for information displays (4 functions total)
 */

/* EDIT_INFO -- Allow the user to alter some of the information */
extern void edit_info PL_(( int line, int choice ));

/* GOD_ARMYEDIT -- Adjust an army in god mode */
extern void god_armyedit PL_(( int line, int choice, int armynum ));

/* GOD_CVNEDIT -- Adjust a caravan in god mode */
extern void god_cvnedit PL_(( int line, int cvnnum ));

/* GOD_NAVYEDIT -- Adjust a navy in god mode */
extern void god_navyedit PL_(( int line, int navynum ));

/* ============================================================================
 * INFORMATION DISPLAY INTERFACE - infoG.c
 * ============================================================================
 * Purpose: Formatted information displays and data presentation
 * Usage: Information screens, data formatting, content display
 * Notes: Core information display system (12 functions total)
 */

/* SHOW_CITY_INFO -- Filter to call the show_info routine */
extern int show_city_info PL_(( void ));

/* SHOW_INFO -- Page through information on a selected item */
extern int show_info PL_(( int inchoice ));

/* ============================================================================
 * INPUT/OUTPUT INTERFACE SYSTEM - ioG.c
 * ============================================================================
 * Purpose: User input processing and output formatting system
 * Usage: Input validation, data selection, and formatted output
 * Notes: Core I/O interface for user interaction (23 functions total)
 */

/* System display functions */
extern void copyscreen PL_(( void )); /* Display copyright notice (REQUIRED) */
extern void create_help PL_(( char * title, KLIST_PTR kl_ptr, PARSE_PTR fnc_l, int lim )); /* Build help system */
extern void motd_display PL_(( void )); /* Show message of the day */

/* Data input and selection functions */
extern int enter_unittype PL_(( int style, char * prompt, char * emsg )); /* Select army unit type */
extern int get_altitude PL_(( void )); /* Enter altitude type */
extern int get_country PL_(( int allinp )); /* Get nation selection */
extern int get_designation PL_(( void )); /* Enter major designation */
extern int get_diplomacy PL_(( int oldstatus, int othstatus )); /* Get diplomacy status */
extern DMODE_PTR get_dmode PL_(( char * prompt )); /* Enter major designation mode */
extern FNCI get_func PL_(( KEYSYS_STRUCT key_info )); /* Get bindable function */
extern int get_mindesg PL_(( void )); /* Enter minor designation */
extern int get_mtrls PL_(( itemtype * m1_ptr )); /* Select materials */
extern int get_tgclass PL_(( void )); /* Enter tradegood class */
extern int get_tradegood PL_(( void )); /* Enter tradegood type */
extern int get_vegetation PL_(( void )); /* Enter vegetation type */

/* Output and display functions */
extern void dump_ntn_info PL_(( void )); /* Dump nation info (machine readable) */
extern void gaudy_lineout PL_(( int loc, char * str )); /* Highlighted nation output */
extern void normal_lineout PL_(( int loc, char * str )); /* Standard string output */
extern void show_scores PL_(( void )); /* Display nation scores */
extern int spawn_out PL_(( void )); /* Spawn shell interface */

/* ============================================================================
 * DATA I/O INTERFACE SYSTEM - iodataG.c
 * ============================================================================ 
 * Purpose: File system interaction and data persistence management
 * Usage: Nation login/logout, file monitoring, game state management
 * Notes: Critical system for multi-user data coordination (14 functions total)
 */

/* ARETHEYON -- returns TRUE if 'country' is logged on, else FALSE */
extern int aretheyon PL_(( void ));

/* BYE -- Clean up everything prior to exiting */
extern void bye PL_(( void ));

/* CLOSE_NTN -- unset and close up nation information */
extern void close_ntn PL_(( int ntnnum, char * realname ));

/* FILES_CHECK -- Periodically check if various files need accessing */
extern void files_check PL_(( void ));

/* GET_GOD -- Routine to query god as to what nation to become */
extern int get_god PL_(( int natn, int nobrowse ));

/* MAX_DESCRIPT -- The maximum number of descriptors available */
extern int max_descript PL_(( void ));

/* MBOX_CHECK -- Check if the mail needs reading */
extern void mbox_check PL_(( void ));

/* NEWS_CHECK -- Check if the news needs reading */
extern void news_check PL_(( void ));

/* OPEN_NTN -- initialize all nation information */
extern int open_ntn PL_(( int ntnnum ));

/* RESET_GOD -- Restore settings of god */
extern void reset_god PL_(( void ));

/* SAVE_GOD -- Go and get rid of god locks from his tramping around */
extern void save_god PL_(( void ));

/* STMAIL_INIT -- Initialize the system mail checking setup */
extern void stmail_init PL_(( void ));

/* SYSM_CHECK -- Check if the system mail needs reading */
extern void sysm_check PL_(( void ));

/* ============================================================================
 * KEY BINDING SYSTEM - keybindG.c  
 * ============================================================================
 * Purpose: Keyboard binding configuration and management system
 * Usage: Key assignment, function mapping, user input customization
 * Notes: Sophisticated customizable input system (15 functions total)
 */

/* ALIGN_GLOBAL_KEYS -- Align all of the global keys */
extern void align_global_keys PL_(( void ));

/* BIND_KEYS -- Attach a key binding to the list */
extern void bind_keys PL_(( KLIST_PTR * klist_ptr, char * kstr, FNCI f_ptr ));

/* CHECK_KEYS -- Verify that the key bindings are set properly */
extern int check_keys PL_(( KLIST_PTR * l_of_keys, KEYSYS_STRUCT key_info ));

/* FIND_FUNC -- Return the pointer to the function information */
extern PARSE_PTR find_func PL_(( FNCI f_ptr, PARSE_PTR p_list, int maxnum ));

/* FIND_KEYS -- Locate a key binding from within the list */
extern KLIST_PTR find_keys PL_(( KLIST_PTR klist_ptr, char * kstr ));

/* FREE_KEYS -- Free up the memory of the key bindings */
extern void free_keys PL_(( KLIST_PTR * klist_ptr ));

/* FUNC_MATCH -- Return the matching function given the string name */
extern FNCI func_match PL_(( char * namestr, PARSE_PTR p_list, int maxnum ));

/* GET_KEYS -- Read in a list of keys to be bound */
extern int get_keys PL_(( char * pr_str, char * out_str ));

/* INIT_KEYS -- Initialize all of the key bindings */
extern void init_keys PL_(( KLIST_PTR * klist_ptr, KBIND_PTR kbind_list, int numbind ));

/* NUM_BINDINGS -- Report the the number of keys bound to a function */
extern int num_bindings PL_(( KLIST_PTR klist_ptr, FNCI f_ptr ));

/* PARSE -- interpret pending or upcoming keyboard input */
extern void parse PL_(( void ));

/* PARSE_KEYS -- Find a function from the given key list */
extern FNCI parse_keys PL_(( KLIST_PTR klist_ptr, int echo_key ));

/* RM_KEYS -- Remove a key from the list */
extern int rm_keys PL_(( KLIST_PTR * klist_ptr, char * kstr ));

/* SORT_KEYS -- Re-sort the entire key binding list */
extern void sort_keys PL_(( KLIST_PTR * klist_ptr ));

/* ============================================================================
 * MAGIC SYSTEM INTERFACE - magicG.c
 * ============================================================================
 * Purpose: Magic power display and spell casting interface
 * Usage: Spell selection, power management, magical abilities interface
 * Notes: Complete magic system UI with power display (25 functions total)
 */

/* ALIGN_MAGIC_KEYS -- Align all of the magic system keys */
extern void align_magic_keys PL_(( void ));

/* CAST_SPELLS -- Allow the nation to cast a spell from the unit */
extern int cast_spells PL_(( void ));

/* SHOW_MAGIC -- Display and adjust all of the magic powers for the nation */
extern int show_magic PL_(( void ));

/* ============================================================================
 * MAIL READING INTERFACE - mailG.c
 * ============================================================================
 * Purpose: In-game mail system interface and message management
 * Usage: Mail reading, message navigation, mail system control
 * Notes: Comprehensive mail reader with full message system (43 functions total)
 */

/* ALIGN_READER_KEYS -- Align all of the mail reader keys */
extern void align_reader_keys PL_(( void ));

/* DO_EMAIL -- Send a normal mail message */
extern int do_email PL_(( void ));

/* RMAIL_CLOSE -- Store the mail messages and remove the lock */
extern void rmail_close PL_(( void ));

/* RMAIL_PARSE -- Peruse all of the mail for the user */
extern int rmail_parse PL_(( void ));

/* ============================================================================
 * MISCELLANEOUS INTERFACE - miscG.c
 * ============================================================================
 * Purpose: Main command processing and general interface functions
 * Usage: Primary command parsing, reporting, game state management
 * Notes: Core command processing system with reports (30 functions total)
 */

/* ARMY_REPORT -- Show the army information for the nation */
extern int army_report PL_(( void ));

/* CAMP_INFO -- display information about current data file */
extern int camp_info PL_(( void ));

/* CVN_REPORT -- Show the caravan information for the nation */
extern int cvn_report PL_(( void ));

/* DO_CJUMP -- Go to the capital of the nation */
extern int do_cjump PL_(( void ));

/* DO_DIPLOMACY -- Show the nation diplomacy screens */
extern int do_diplomacy PL_(( void ));

/* DO_HELP -- Provide the player with some documentation */
extern int do_help PL_(( void ));

/* DO_IGNORE -- Ignore the keystrokes */
extern int do_ignore PL_(( void ));

/* DO_MJUMP -- Go to the marked sector */
extern int do_mjump PL_(( void ));

/* DO_MOTDEDIT -- Try to edit the motd file */
extern int do_motdedit PL_(( void ));

/* DO_MOVEPEOP -- Relocate people from the current sector */
extern int do_movepeop PL_(( void ));

/* DO_NARMY -- Go to the next army in the nation */
extern int do_narmy PL_(( void ));

/* DO_NCVN -- Go to the next caravan in the nation */
extern int do_ncvn PL_(( void ));

/* DO_NNAVY -- Go to the next fleet in the nation */
extern int do_nnavy PL_(( void ));

/* DO_OPTIONS -- Select and adjust the global options */
extern int do_options PL_(( void ));

/* DO_PAPER -- Select a newspaper for reading */
extern int do_paper PL_(( void ));

/* DO_QUIT -- goodbye cruel world! */
extern int do_quit PL_(( void ));

/* DO_REFRESH -- Refresh the screen */
extern int do_refresh PL_(( void ));

/* DO_RELOGIN -- Attempt to login as another nation */
extern int do_relogin PL_(( void ));

/* DO_SARMY -- Go to a specified army */
extern int do_sarmy PL_(( void ));

/* DO_SCITY -- Go to the specified city */
extern int do_scity PL_(( void ));

/* DO_SCORE -- Show the score of the nations in the world */
extern int do_score PL_(( void ));

/* DO_SCVN -- Go to the specified caravan */
extern int do_scvn PL_(( void ));

/* DO_SJUMP -- Go to the specified sector */
extern int do_sjump PL_(( void ));

/* DO_SNAVY -- Go to a specified naval unit */
extern int do_snavy PL_(( void ));

/* DO_UNIMPLEMENTED -- Just indicate that this function is not yet done */
extern int do_unimplemented PL_(( void ));

/* GROUP_REPORT -- Show the army information for a particular sector */
extern int group_report PL_(( void ));

/* NAVY_REPORT -- Show the navy information for the nation */
extern int navy_report PL_(( void ));

/* OPTION_CMD -- Adjust some options */
extern void option_cmd PL_(( KEYSYS_STRUCT key_info, KLIST_PTR * list_of_keys ));

/* ============================================================================
 * MOVEMENT INTERFACE - moveG.c
 * ============================================================================
 * Purpose: Interactive unit and item movement system
 * Usage: Unit relocation, movement interface, path planning
 * Notes: Core movement interface with relocation system (24 functions total)
 */

/* ALIGN_MOVE_KEYS -- Align all of the movement keys */
extern void align_move_keys PL_(( void ));

/* MOVE_PARSE -- relocate a unit using an interface */
extern void move_parse PL_(( int type ));

/* MOVE_RELOCATE -- complete final placement */
extern void move_relocate PL_(( int type, int verbal ));

/* MOVE_SELECT -- Routine to determine if a caravan, army or navy is
                  being moved.                                       */
extern int move_select PL_(( void ));

/* MOVE_STVAL -- String representation of the movement cost */
extern void move_stval PL_(( char * out_str, int mval, int cmpct ));

/* ============================================================================
 * NAVY MANIPULATION INTERFACE - navyG.c
 * ============================================================================
 * Purpose: Naval unit management and fleet operations interface
 * Usage: Navy manipulation, fleet commands, maritime operations
 * Notes: Complete naval interface system with transport (14 functions total)
 */

/* DISB_NAVY -- Get rid of a naval unit */
extern void disb_navy PL_(( NAVY_PTR n1_ptr ));

/* EXT_NAVYCMD -- Perform an extended navy operation */
extern void ext_navycmd PL_(( int navie ));

/* EXT_NAVYINFO -- Provide extended information about the naval fleet */
extern void ext_navyinfo PL_(( NAVY_PTR n1_ptr ));

/* NAVY_REPAIR -- Attempt to repair a navy */
extern void navy_repair PL_(( NAVY_PTR n1_ptr ));

/* NAVY_TRANSPORT -- Load/Unload the given naval unit */
extern void navy_transport PL_(( NAVY_PTR n1_ptr ));

/* SUPPLY_NAVY -- Attempt to set the supply value of a navy unit */
extern int supply_navy PL_(( NAVY_PTR n1_ptr, int level, int doquery ));

/* ============================================================================
 * NATION INFORMATION INTERFACE - ntninfoG.c
 * ============================================================================
 * Purpose: Nation information display and statistics screen
 * Usage: Nation data presentation, statistics viewing, info management
 * Notes: Comprehensive nation information system (30+ functions total)
 */

/* ALIGN_NINFO_KEYS -- Align all of the nation information mode keys */
extern void align_ninfo_keys PL_(( void ));

/* NTN_INFO - this is the nation information screen routine */
extern int ntn_info PL_(( void ));

/* ============================================================================
 * FILE PAGING INTERFACE - pagerG.c
 * ============================================================================
 * Purpose: File viewing and text display system
 * Usage: File reading, text browsing, news display
 * Notes: Specialized paging system for game content (19 functions total)
 */

/* PAGE_FILE -- Peruse the specified file, reading appropriately */
extern int page_file PL_(( char * fname, int news ));

/* ============================================================================
 * REGION MANAGEMENT INTERFACE - regionG.c
 * ============================================================================
 * Purpose: Supply region command processing and management
 * Usage: Regional commands, supply center operations, area management
 * Notes: Regional command system for supply operations (2 functions total)
 */

/* ADJUST_REGION -- Affect a change on a region */
extern void adjust_region PL_(( int x, int y ));

/* REGION_CMD -- Attempt to send commands to the current supply center */
extern int region_cmd PL_(( void ));

/* ============================================================================
 * SECTOR MANAGEMENT INTERFACE - sectorG.c
 * ============================================================================
 * Purpose: Sector manipulation and terrain management commands
 * Usage: Sector designation, construction, terrain modification
 * Notes: Core sector management interface (3 functions total)
 */

/* CHANGE_DESG -- Adjust the major designation of a sector */
extern int change_desg PL_(( void ));

/* CONSTRUCT -- construct minor designations */
extern int construct PL_(( void ));

/* SECT_INFO -- Provide more detailed information on the current sector */
extern void sect_info PL_(( void ));

/* ============================================================================
 * UNIT SELECTION INTERFACE - selectG.c
 * ============================================================================
 * Purpose: Unit selection and navigation system
 * Usage: Unit targeting, selection management, goto operations
 * Notes: Core selection system with navigation (16 functions total)
 */

/* EXT_CMD -- Perform an extend command on a selected unit */
extern int ext_cmd PL_(( void ));

/* GET_ARMYSELECT -- If current selection is an army return it */
extern ARMY_PTR get_armyselect PL_(( void ));

/* GET_CVNSELECT -- If current selection is a caravan return it */
extern CVN_PTR get_cvnselect PL_(( void ));

/* GET_NAVYSELECT -- If current selection is a navy return it */
extern NAVY_PTR get_navyselect PL_(( void ));

/* GOTO_ARMY -- set the current sector and selector to the desired army */
extern int goto_army PL_(( int idnum ));

/* GOTO_CITY -- set the current sector to the desired city */
extern void goto_city PL_(( CITY_PTR c1_ptr ));

/* GOTO_CVN -- set the current sector and selector to the desired caravan */
extern int goto_cvn PL_(( int idnum ));

/* GOTO_NAVY -- set the current sector and selector to the desired navy */
extern int goto_navy PL_(( int idnum ));

/* PICK_NEXT -- Select the unit one below the current unit */
extern int pick_next PL_(( void ));

/* PICK_PREVIOUS -- Select the unit one above the current unit */
extern int pick_previous PL_(( void ));

/* SET_ARMYSELECT -- Set the selection indicator to the desired army */
extern void set_armyselect PL_(( int idnum ));

/* SET_CVNSELECT -- Set the selection indicator to the desired caravan */
extern void set_cvnselect PL_(( int idnum ));

/* SET_NAVYSELECT -- Set the selection indicator to the desired navy */
extern void set_navyselect PL_(( int idnum ));

/* SET_SELECT -- Allow adjustment to the selector */
extern int set_select PL_(( int type, char * desc ));

/* TRANS_CMD -- Load or unload the currently selected caravan or navy */
extern int trans_cmd PL_(( void ));

/* ============================================================================
 * TRANSFER SYSTEM INTERFACE - xferG.c
 * ============================================================================
 * Purpose: Item transfer mechanism between storage locations
 * Usage: Resource transfer, inventory management, item exchange
 * Notes: Comprehensive transfer system with multi-source support (38 functions total)
 */

/* ALIGN_XFER_KEYS -- Align all of the transfer mode keys */
extern void align_xfer_keys PL_(( void ));

/* CITY2XFER -- Copy a city structure into the indicated xfer slot */
extern void city2xfer PL_(( int slot, CITY_PTR c1_ptr ));

/* CVN2XFER -- Copy a carvan structure into the indicated xfer slot */
extern void cvn2xfer PL_(( int slot, CVN_PTR v1_ptr ));

/* NAVY2XFER -- Copy a navy structure into the indicated xfer slot */
extern void navy2xfer PL_(( int slot, NAVY_PTR n1_ptr ));

/* SCT2XFER -- Copy information about a sector into the current slot */
extern void sct2xfer PL_(( int slot, int xloc, int yloc ));

/* XFER2CITY -- Shift the results back into the city structure */
extern void xfer2city PL_(( int slot, CITY_PTR c1_ptr ));

/* XFER2CVN -- Finalize the changes made on the caravan baggage */
extern void xfer2cvn PL_(( int slot, CVN_PTR v1_ptr ));

/* XFER2NAVY -- Finalize the changes made on the commodity */
extern void xfer2navy PL_(( int slot, NAVY_PTR n1_ptr ));

/* XFER2SCT -- Return the transferred materials to the sector */
extern void xfer2sct PL_(( int slot, int xloc, int yloc ));

/* XFER_INIT -- Initialize the keybindings, if needed, and other things */
extern int xfer_init PL_(( void ));

/* XFER_MODE -- Interactively transfer items between two storage elements */
extern void xfer_mode PL_(( void ));

/* ============================================================================
 * TIME CHECKING INTERFACE - time_ckG.c
 * ============================================================================
 * Purpose: Time validation and host access verification system
 * Usage: Time restrictions, host checking, access control
 * Notes: Security system for time/host validation (11 functions total)
 */

/* INITIAL_CHECK -- Initial time/host check. */
extern int initial_check PL_(( void ));

/* INIT_TIME_CHECK -- Initialize time check stuff */
extern void init_time_check PL_(( void ));

#undef PL_
#endif /* __CEXTRACT__ */
