/*
 * fileA.h - Core Game Engine Function Prototypes
 *
 * This header contains function prototypes for the core game engine modules
 * that implement the fundamental game mechanics of the Conquer strategy game.
 * Originally auto-generated by cextract 1.5, this file provides the interface
 * definitions for game engine subsystems including combat, economics, world
 * creation, nation management, and turn processing.
 *
 * Key Components:
 *   - Core game engine function prototypes from mainA.c through updateA.c
 *   - Combat system interfaces for battle resolution and damage calculation
 *   - Economic system interfaces for resource production and consumption
 *   - World generation interfaces for map creation and resource placement
 *   - Nation management interfaces for NPC behavior and player interactions
 *   - Turn processing interfaces for game state updates and progression
 *
 * Integration Notes:
 *   - Used by: Game engine modules requiring cross-module function calls
 *   - Used by: Client interface modules needing game engine functionality
 *   - Depends on: header.h (basic type definitions and game constants)
 *   - Provides: Complete game engine API for all core subsystems
 *
 * Modernization Considerations:
 *   - Legacy ANSI C prototype compatibility macros (PL_) should be removed
 *   - Function prototypes should be converted to modern C2023 syntax
 *   - Parameter types should be explicitly specified instead of using macros
 *   - Include guards should be modernized to standard conventions
 *   - Documentation should be moved inline with function declarations
 *
 * Historical Notes:
 *   - Auto-generated by cextract 1.5 on Tue Oct 20 18:11:31 1992
 *   - Contains legacy pre-ANSI C compatibility mechanisms
 *   - Represents the complete game engine interface as of original development
 */

/*
 * Legacy ANSI C Compatibility Macros
 *
 * These macros provide compatibility between pre-ANSI C compilers that don't
 * support function prototypes and ANSI C compilers that do. In modern C2023,
 * these should be removed and replaced with standard function prototypes.
 *
 * PL_(x) - Parameter list macro for conditional prototype support
 *   - Expands to 'x' on ANSI C compilers (__STDC__ defined)
 *   - Expands to '( )' on pre-ANSI C compilers (no prototype support)
 *
 * Modernization: Remove PL_ macro usage and use direct function prototypes
 */
#ifndef __CEXTRACT__
#if __STDC__
#define PL_(x) x
#else
#define PL_(x) ( )
#endif /* __STDC__ */

/* ============================================================================
 * MAIN PROGRAM INTERFACE - mainA.c
 * ============================================================================
 * Purpose: Core program entry point and command-line processing
 * Usage: Program initialization, option parsing, and main control flow
 * Notes: Primary entry point for the Conquer game engine
 */

/*
 * main - Program entry point and command-line option processor
 *
 * Primary entry point for the Conquer game engine that handles command-line
 * argument parsing, initializes game systems, and controls the main program
 * execution flow. Processes options for game modes, configuration settings,
 * and operational parameters.
 *
 * Parameters:
 *   argc - Number of command-line arguments including program name
 *   argv - Array of command-line argument strings
 *
 * Returns:
 *   0 on successful program completion
 *   Non-zero exit code on error or abnormal termination
 *
 * Side Effects:
 *   - Initializes global game state and configuration
 *   - May modify global variables based on command-line options
 *   - Sets up game environment and data structures
 *
 * Notes:
 *   - Standard C main function signature
 *   - Handles all command-line processing for the game engine
 *   - Controls overall program execution and shutdown
 */
extern int main PL_(( int argc, char ** argv ));

/* ============================================================================
 * NATION CREATION AND USER MANAGEMENT - adduserA.c
 * ============================================================================
 * Purpose: New player registration and nation creation system
 * Usage: Player onboarding, nation setup, and NPC management
 * Notes: Handles both human player and computer-controlled nation creation
 */

/*
 * newlogin - Create a new nation specification for a player
 *
 * Creates a new nation entry for either a human player or computer-controlled
 * nation, handling the complete setup process including initial resources,
 * starting location, race selection, and basic nation configuration.
 *
 * Parameters:
 *   makenpcs - Flag indicating whether to create NPC nations (non-zero) or
 *              human player nation (zero)
 *
 * Returns:
 *   Non-zero on successful nation creation
 *   0 on failure (invalid parameters, resource constraints, etc.)
 *
 * Side Effects:
 *   - Modifies global nation data structures
 *   - May allocate starting resources and territories
 *   - Updates world state with new nation presence
 *
 * Notes:
 *   - Part of the player registration and game setup process
 *   - Used for both initial game setup and mid-game nation addition
 */
extern int newlogin PL_(( int makenpcs ));

/*
 * read_npc - Load specified number of NPC nations from data files
 *
 * Reads computer-controlled nation data from persistent storage, loading
 * the specified number of NPC nations into the game world. Used during
 * game initialization to populate the world with AI-controlled entities.
 *
 * Parameters:
 *   amount - Number of NPC nations to read and load into the game
 *
 * Returns:
 *   None (void function)
 *
 * Side Effects:
 *   - Loads NPC data into global nation structures
 *   - May modify world state to reflect NPC presence
 *   - Initializes AI behavior parameters for loaded nations
 *
 * Notes:
 *   - Used during game world initialization
 *   - Coordinates with file I/O systems for data persistence
 */
extern void read_npc PL_(( int amount ));

/*
 * write_npc - Save NPC nation data to persistent storage
 *
 * Writes computer-controlled nation data to data files for persistence
 * across game sessions. Saves current NPC state including territories,
 * resources, military units, and AI behavior parameters.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   Non-zero on successful write operation
 *   0 on failure (file I/O error, data corruption, etc.)
 *
 * Side Effects:
 *   - Writes data to persistent storage files
 *   - May create or modify NPC data files
 *   - Updates file timestamps and metadata
 *
 * Notes:
 *   - Critical for game state persistence
 *   - Should be called during save operations and turn processing
 */
extern int write_npc PL_(( void ));

/* ============================================================================
 * COMBAT SYSTEM INTERFACE - combatA.c
 * ============================================================================
 * Purpose: Battle resolution and damage calculation system
 * Usage: Military conflict processing and combat mechanics
 * Notes: Core combat engine for all military interactions
 */

/*
 * combat - Main combat resolution controller
 *
 * Primary controller function that manages the complete combat resolution
 * process for all military engagements in the game world. Handles battle
 * initiation, damage calculation, casualty resolution, and post-combat
 * effects for armies, navies, and siege operations.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 *
 * Side Effects:
 *   - Modifies military unit statistics and positions
 *   - May cause unit destruction or retreat
 *   - Updates sector control and ownership
 *   - Generates combat reports and messages
 *
 * Notes:
 *   - Called during turn processing to resolve all pending conflicts
 *   - Coordinates with messaging system for battle reports
 */
extern void combat PL_(( void ));

/*
 * combat_roll - Generate random combat outcome value
 *
 * Generates a random combat roll value between 0 and 100 used for battle
 * resolution calculations. Provides the random component for combat
 * outcomes, determining hit probability, damage amounts, and special
 * combat events.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   Random integer value between 0 and 100 inclusive
 *
 * Side Effects:
 *   - Advances random number generator state
 *   - No persistent state modifications
 *
 * Notes:
 *   - Core randomization function for combat calculations
 *   - Used throughout combat system for various probability checks
 */
extern int combat_roll PL_(( void ));

/*
 * init_combat_roll - Initialize combat random number generation
 *
 * Initializes the random number generation system used for combat
 * calculations, setting up seed values and ensuring proper randomization
 * for battle outcomes. Called during game initialization to prepare
 * the combat system.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 *
 * Side Effects:
 *   - Initializes random number generator state
 *   - Sets up combat randomization parameters
 *   - May seed from system time or configuration
 *
 * Notes:
 *   - Should be called once during game startup
 *   - Essential for fair and unpredictable combat outcomes
 */
extern void init_combat_roll PL_(( void ));

/* ============================================================================
 * WORLD CONFIGURATION SYSTEM - configA.c
 * ============================================================================
 * Purpose: World generation configuration and parameter setup
 * Usage: Game world initialization and scenario configuration
 * Notes: Controls world creation parameters and settings
 */

/*
 * bld_config - Configure world generation parameters
 *
 * Sets up the configuration parameters for world generation, including
 * terrain settings, resource distribution, nation placement, and other
 * world creation variables. Controls how the game world will be built.
 *
 * Parameters:
 *   buildit - Flag indicating whether to actually build the world (non-zero)
 *             or just configure parameters (zero)
 *
 * Returns:
 *   Non-zero on successful configuration
 *   0 on configuration failure
 */
extern int bld_config PL_(( int buildit ));

/*
 * makeworld - Primary world creation controller
 *
 * Main controller function for world generation that coordinates the
 * complete world creation process. Handles terrain generation, resource
 * placement, nation setup, and scenario loading when specified.
 *
 * Parameters:
 *   rflag - Flag indicating whether to read a scenario file (non-zero)
 *           or generate a new random world (zero)
 *
 * Returns:
 *   None (void function)
 */
extern void makeworld PL_(( int rflag ));

/*
 * zeroworld - Initialize world data structures to empty state
 *
 * Initializes all world data structures to a clean, empty state in
 * preparation for world generation or scenario loading. Clears all
 * existing world data and prepares for new world creation.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void zeroworld PL_(( void ));

/* ============================================================================
 * WORLD GENERATION SYSTEM - createA.c
 * ============================================================================
 * Purpose: Actual world generation and terrain creation
 * Usage: Generate game world terrain, features, and resources
 * Notes: Implements the core world generation algorithms
 */

/*
 * createworld - Generate new game world
 *
 * Generates a new game world with terrain, geographic features,
 * climate zones, and basic world structure. Creates the foundation
 * for resource placement and nation development.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void createworld PL_(( void ));

/*
 * rawmaterials - Place resources throughout the world
 *
 * Places valuable resources including jewels, metals, and trade goods
 * throughout the generated world. Determines resource distribution
 * and abundance based on terrain and world generation parameters.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void rawmaterials PL_(( void ));

/* ============================================================================
 * ECONOMIC SYSTEM INTERFACE - economyA.c
 * ============================================================================
 * Purpose: Economic simulation and resource management
 * Usage: Turn-based economic updates and resource distribution
 * Notes: Core economic engine for resource production and consumption
 */

/*
 * upd_consume - Process resource consumption for all nations
 *
 * Handles resource consumption calculations for all nations during
 * turn processing, including population needs, military maintenance,
 * and industrial consumption requirements.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void upd_consume PL_(( void ));

/*
 * upd_produce - Process resource production for all sectors
 *
 * Calculates and distributes resource production from all productive
 * sectors to their controlling nations, handling mining, agriculture,
 * and industrial output.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void upd_produce PL_(( void ));

/*
 * upd_sectors - Update sector status and siege conditions
 *
 * Updates the status of all world sectors including siege conditions,
 * ownership changes, defensive preparations, and sector-specific
 * economic and military factors.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void upd_sectors PL_(( void ));

/* ============================================================================
 * MESSAGING SYSTEM INTERFACE - mailA.c
 * ============================================================================
 * Purpose: In-game messaging and news distribution system
 * Usage: Send reports, news, and communications to nations
 * Notes: Comprehensive messaging system for game events and communications
 */

/* Complete messaging system functions - 13 total functions documented in mailA.c */
extern void msg_cadjust PL_(( int ntarget, char * nheader )); /* Adjust message target/header */
extern void msg_cfinish PL_(( int sendit )); /* Finish and deliver current message */
extern void msg_cinit PL_(( char * headstr )); /* Initialize new message */
extern void msg_cmark PL_(( void )); /* Mark position for later insertion */
extern void msg_conquer PL_(( char * str )); /* Add line to pending message */
extern void msg_creturn PL_(( char * str )); /* Insert text at marked position */
extern void msg_csend PL_(( void )); /* Send pending message */
extern void msg_cunmark PL_(( void )); /* Remove mark from list */
extern void msg_gfinish PL_(( void )); /* Finish group messaging */
extern void msg_ginit PL_(( char * str )); /* Initialize group message */
extern void msg_grouped PL_(( ntntype to, int xloc, int yloc, char * msgstr )); /* Add to group message */
extern void send_sortednews PL_(( void )); /* Send accumulated sorted news */
extern void sorted_news PL_(( int cntry, char * line )); /* Store news for sorting */

/* ============================================================================
 * MISCELLANEOUS UTILITIES - miscA.c
 * ============================================================================
 * Purpose: General utility functions for game engine
 * Usage: Statistics, testing, name generation, and utility operations
 * Notes: Supporting functions for various game systems (7 functions total)
 */

extern void dice_tester PL_(( void )); /* Test random number generation */
extern void mark_leaders PL_(( void )); /* Mark leader influence areas */
extern void ntn_stats PL_(( NTN_PTR n1_ptr )); /* Generate nation statistics */
extern void random_name PL_(( char * str, int race )); /* Generate random names */
extern void sort_news PL_(( int newsturn )); /* Sort newspaper entries */
extern void world_stats PL_(( void )); /* Display world statistics */

/* ============================================================================
 * MONSTER/NPC BEHAVIOR SYSTEM - monsterA.c
 * ============================================================================
 * Purpose: AI behavior for computer-controlled monster nations
 * Usage: Monster AI updates and behavior processing
 * Notes: Specialized AI for different monster types (9 functions total)
 */

extern void monster_growth PL_(( void )); /* Expand monster resources */
extern void monster_move_army PL_(( int vtype, int etype )); /* Move monster armies */
extern void upd_lizards PL_(( void )); /* Update lizard nation behavior */
extern void upd_nomads PL_(( void )); /* Update nomadic tribe behavior */
extern void upd_pirates PL_(( void )); /* Update pirate nation behavior */
extern void upd_savages PL_(( void )); /* Update savage nation behavior */

/* ============================================================================
 * NPC MOVEMENT SYSTEM - moveA.c
 * ============================================================================
 * Purpose: Computer-controlled unit movement and pathfinding
 * Usage: AI movement decisions and unit relocation
 * Notes: Movement AI for computer-controlled military units
 */

extern int npc_movearmy PL_(( int x, int y )); /* Move NPC army to location */

/* ============================================================================
 * NPC NATION AI SYSTEM - npcA.c
 * ============================================================================
 * Purpose: Computer-controlled nation AI and decision making
 * Usage: AI turn processing and strategic decisions
 * Notes: High-level AI for computer-controlled nations
 */

extern void move_for_ntn PL_(( void )); /* Process nation turn movement */
extern void rove_army PL_(( void )); /* Army roving behavior */

/* ============================================================================
 * SECTOR CONTROL SYSTEM - sectorA.c
 * ============================================================================
 * Purpose: Territory control, conquest, and siege mechanics
 * Usage: Land ownership changes and military control calculations
 * Notes: Core territorial control and siege system (19 functions total)
 */

extern void capture_land PL_(( ntntype whom, int xloc, int yloc )); /* Transfer sector ownership */
extern void change_reach PL_(( int xloc, int yloc, int value )); /* Modify reach values */
extern void flee_people PL_(( long amount, int xloc, int yloc )); /* Population fleeing */
extern int get_reach PL_(( int xloc, int yloc )); /* Check reach status */
extern long men_to_capture PL_(( int xloc, int yloc, ntntype by )); /* Calculate capture requirements */
extern void set_reach PL_(( int xloc, int yloc, int value )); /* Set reach values */
extern void set_relocation PL_(( int xloc, int yloc )); /* Configure relocation reach */
extern void upd_capture PL_(( void )); /* Process ownership changes */

/* ============================================================================
 * TURN PROCESSING SYSTEM - updateA.c
 * ============================================================================
 * Purpose: Main turn processing and game state updates
 * Usage: Complete turn calculation and world state advancement
 * Notes: Master controller for all turn-based game updates
 */

/*
 * update - Main turn processing controller
 *
 * Master controller function that coordinates all turn processing
 * activities including economic updates, military actions, diplomatic
 * changes, and world state advancement. Processes a complete game turn.
 *
 * Parameters:
 *   None
 *
 * Returns:
 *   None (void function)
 */
extern void update PL_(( void ));

/*
 * upd_military - Process military updates for a nation
 *
 * Handles all military-related updates for a specific nation including
 * army movement, naval operations, caravan activities, and military
 * unit maintenance and actions.
 *
 * Parameters:
 *   cntry - Nation number to process military updates for
 *
 * Returns:
 *   None (void function)
 */
extern void upd_military PL_(( int cntry ));

/*
 * upd_nations - Process nation statistics and population updates
 *
 * Updates population growth, nation statistics, demographic changes,
 * and other nation-level calculations for the specified nation or
 * all nations during turn processing.
 *
 * Parameters:
 *   which - Nation number to update, or special value for all nations
 *
 * Returns:
 *   None (void function)
 */
extern void upd_nations PL_(( int which ));

#undef PL_
#endif /* __CEXTRACT__ */
